### ISSUE TITLE
Modern versions of Chrome/Safari/Edge/Firefox

### ISSUE THREAD

**Issue by o-t-w** [Fall-Back/CSS-Mustard-Cut#2]
Hi Andy. Great work on this. 

The M3 cut specifies a way to cut out IE10 and 11, but still goes _very_ far back in support for every other browser. Ideally i'm looking to cut out any browser that doesn't support CSS custom properties, but without the CSS being dependent on JavaScript. I'd definitely settle for a media query that just cuts out a larger swathe of old Chrome/Safari/Edge/Firefox versions though. Do you have any ideas?

**Comment by andykirk** [comment]
Hi,

I've been meaning to look into this for a while when I have time. 

If you're specifically after support for custom properties, the safest way is to wrap all your CSS in an @supports block. 
It won't stop the CSS from loading, but the effect would be the same.

**Comment by o-t-w** [comment]
Yes I had assumed that you couldn't do any real feature detection like that without loading with JS, but sending a large CSS file to browsers that can't use it seems a shame. I'll keep my eye open for a modern-only media query.

Do you know how your M3 cut does with mobile browsers like Opera Mini, UC browser etc?

**Comment by andykirk** [comment]
Can you @import inside an @supports block? I haven't tried it or read up on that.

Opera Mini in Opera Mini mode is rejected by the cut, but as you can't use Opera Mini without JS, you can use JS to load the CSS for Opera Mini if you want to support it (see the SitePoint article).
UC Browser is a bit of an odd one as there are loads of 'flavours' of it. It works in the normal ones, but not the 'mini' ones (if they're still a thing)?
I tested extensively at the time of writing, but things have moved on in the browserscape, so I can't be 100% sure if there are any edge cases, but I'd generally expect the M3 cut to permit all up-to-date browsers except for 'Mini'.

Using the `media` attribute on `<link>`s is the only non-js way I've found to conditionally prevent a stylesheet from loading but using media queries to detect support was never ideal. More modern browsers support more stuff than they ever did, so it's becoming harder to find cases queries fail in order to cut support.
I use [browser strangeness](https://browserstrangeness.github.io/css_hacks.html) as my go-to resource for hacks.

**Comment by andykirk** [comment]
Update. Just checked and you can't use @import inside @supports. I actually knew that, but I'd forgotten.

Personally, if someone is using a browser that's been cut out of CSS support, I don't have too much of a problem with them loading CSS they can't use. It's a shame, but it's not the end of the world.

**Comment by andykirk** [comment]
According to [caniue](https://caniuse.com/#feat=css-variables) Custom Properties can be used in FF from v31+. The nearest known MQ on browser strangeness to that version permits FF47+

```
min--moz-device-pixel-ratio:0) and (display-mode:browser), (min--moz-device-pixel-ratio:0) and (display-mode:fullscreen)
```
It should be possible to swap out the FF line to bump up FF support, but needs testing.

Note that any time the Cut changes, it needs to the checked everywhere just in case.
I’ll do that when I can.

**Comment by o-t-w** [comment]
Would removing the line ` only all and (-webkit-min-device-pixel-ratio:0) and (min-color-index:0),` bump up the version of Safari to 9?

**Comment by andykirk** [comment]
Good call. You're right. I've just tested this and more modern browsers support the pointer queries along with edge, so removing that line does indeed boost the supported versions. Thanks for that!

I've added a new Even More Modern (EM2) cut with the new FF query and that webkit line removed.
Also a mix and match section, now there are enough bits to justify it.

I'm going close this issue now, but happy to chat further if need be.

Thanks again.

**Comment by o-t-w** [comment]
Hi Andy. I just wanted to say thanks again for answering my questions. I cited you and this repo in an article https://alistapart.com/article/the-slow-death-of-internet-explorer-and-future-of-progressive-enhancement
One other approach I should have mentioned in the article is using <script type="module"> to conditionally load JS only on _very_ new browsers.

**Comment by andykirk** [comment]
Hey @o-t-w thanks for that. It’s great to know my work has been useful.
Great article by the way 👍

<script type="module"> is interesting. If you’re using that, how’s it working out? What are you doing about CSS support in those scenarios? Cutting it? Or ?

Cheers

**Comment by o-t-w** [comment]
The cut off is a bit extreme at the moment because Firefox only implemented it in the latest version (they were the last brower to ship). At work were going to try to use `<script type="nomodule">` to deliver a transpiled version of the same code.
For CSS I'll continue to use the cut the media query you came up with 💯

**Comment by andykirk** [comment]
I see. Thanks for the info. I'll think about adding that method to this repo when support is more widespread.
Cheers
